name: flutter_map_vector_tiles_example
description: Example app for flutter_map_vector_tiles.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.0
  flutter_map_vector_tiles:
    path: ../
  latlong2: ">=0.9.1 <0.11.0"

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
